/**
 * /dashboard/api-keys/create — POST-only Route Handler (issue #81).
 *
 * Why a Route Handler instead of a Server Action: Server Actions require a
 * small inline script tag generated by Next.js (the encrypted action ID is
 * kicked off by client JS). A vanilla <form action="/dashboard/api-keys/create"
 * method="post"> works with strict CSP and no JS at all. This is the
 * CSP-friendlier shape the issue asks for.
 *
 * Flow:
 *   1. Form on /dashboard/api-keys/new posts here.
 *   2. We forward the request body to POST /api/api-keys (with the
 *      wb_session cookie).
 *   3. On 201, render an HTML page that displays the raw key ONCE.
 *   4. On 401, redirect to /sign-in (303). On 4xx with an error,
 *      redirect back to /dashboard/api-keys/new?error=… (303).
 *
 * The raw key is rendered into the response body inline — never written to
 * a query parameter, never persisted in the URL, and the page sets
 * Cache-Control: no-store so intermediaries cannot cache it.
 *
 * Spec refs:
 *   §4.1 — API-key auth UI
 *   §5.10 — CSP, no inline scripts, form-action='self'
 *   §2 #20 — no existence leak (we surface only the API's error message)
 *   §2 #22 — keys masked in logs (we never log the raw key here)
 */

import { renderToStaticMarkup } from 'react-dom/server';
import { NextResponse, type NextRequest } from 'next/server';
import { NewKeyResultView } from '../ApiKeysView';

function apiBaseUrl(): string {
  const explicit = process.env['WILLBUY_API_URL'] ?? process.env['NEXT_PUBLIC_API_URL'];
  if (explicit) return explicit.replace(/\/$/, '');
  return 'http://127.0.0.1:3000';
}

function escapeRedirect(s: string): string {
  // Cap length to avoid header bloat; encodeURIComponent for safety.
  return encodeURIComponent(s.slice(0, 200));
}

/**
 * Wrap a presentational view in the same dashboard chrome that
 * /dashboard/layout.tsx applies. We can't reuse the layout from a Route
 * Handler (layouts only wrap pages), so the header is inlined here. The
 * minimal duplication is acceptable for the single one-off result page.
 */
function wrapChrome(inner: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Your new API key — willbuy.dev</title>
    <link rel="stylesheet" href="/_next/static/css/app/layout.css" />
  </head>
  <body class="min-h-screen bg-gray-50">
    <header class="border-b border-gray-200 bg-white">
      <div class="mx-auto flex max-w-5xl items-center justify-between px-6 py-3">
        <a href="/dashboard" class="text-sm font-semibold tracking-tight text-gray-900 hover:text-gray-700">willbuy.dev</a>
        <nav class="flex items-center gap-5 text-sm text-gray-600">
          <a href="/dashboard" class="hover:text-gray-900">Dashboard</a>
          <a href="/dashboard/api-keys" class="hover:text-gray-900">API keys</a>
        </nav>
      </div>
    </header>
    <main>${inner}</main>
  </body>
</html>`;
}

export async function POST(req: NextRequest): Promise<Response> {
  // Parse form-encoded body. URLSearchParams handles application/x-www-form-urlencoded.
  const form = await req.formData();
  const rawLabel = form.get('label');
  const label = typeof rawLabel === 'string' ? rawLabel.trim() : '';

  if (!label) {
    return NextResponse.redirect(
      new URL('/dashboard/api-keys/new?error=Label+is+required', req.url),
      303,
    );
  }

  const cookieHeader = req.headers.get('cookie') ?? '';
  let res: Response;
  try {
    res = await fetch(`${apiBaseUrl()}/api/api-keys`, {
      method: 'POST',
      headers: {
        cookie: cookieHeader,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ label }),
      cache: 'no-store',
    });
  } catch {
    return NextResponse.redirect(
      new URL(
        `/dashboard/api-keys/new?error=${escapeRedirect('API unreachable, please retry')}`,
        req.url,
      ),
      303,
    );
  }

  if (res.status === 401) {
    return NextResponse.redirect(new URL('/sign-in', req.url), 303);
  }
  if (!res.ok) {
    let msg = `Could not create key (${res.status})`;
    try {
      const j = (await res.json()) as { error?: string };
      if (j.error) msg = j.error;
    } catch {
      /* ignore parse errors */
    }
    return NextResponse.redirect(
      new URL(`/dashboard/api-keys/new?error=${escapeRedirect(msg)}`, req.url),
      303,
    );
  }

  const body = (await res.json()) as {
    id: number;
    label: string;
    key: string;
    prefix: string;
  };

  // Render the result view to static HTML. We use renderToStaticMarkup to
  // skip React's data-reactroot etc. — pure HTML keeps the response tiny
  // and CSP-strict (no client hydration).
  const inner = renderToStaticMarkup(
    NewKeyResultView({
      apiKey: body.key,
      label: body.label,
      prefix: body.prefix,
    }),
  );

  return new NextResponse(wrapChrome(inner), {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      // Prevent any intermediary or browser back/forward cache from
      // retaining the raw key. Spec §2 #22 — keys are masked everywhere
      // except this one-time response.
      'cache-control': 'no-store, no-cache, must-revalidate, private',
      pragma: 'no-cache',
      // Stop any embed; the key must not appear in iframes.
      'x-frame-options': 'DENY',
    },
  });
}

// GET for this path is not supported — the user lands here only via form POST.
// A bare GET (e.g. via "Back" navigation) sends them to the form.
export async function GET(req: NextRequest): Promise<Response> {
  return NextResponse.redirect(new URL('/dashboard/api-keys/new', req.url), 303);
}
