/**
 * /dashboard/api-keys/create — POST-only Route Handler (issue #81).
 *
 * Why a Route Handler instead of a Server Action: Server Actions require a
 * small inline script tag generated by Next.js (the encrypted action ID is
 * kicked off by client JS). A vanilla <form action="/dashboard/api-keys/create"
 * method="post"> works with strict CSP and no JS at all. This is the
 * CSP-friendlier shape the issue asks for.
 *
 * Flow:
 *   1. Form on /dashboard/api-keys/new posts here.
 *   2. We forward the request body to POST /api/api-keys (with the
 *      wb_session cookie).
 *   3. On 201, render an HTML page that displays the raw key ONCE.
 *   4. On 401, redirect to /sign-in (303). On 4xx with an error,
 *      redirect back to /dashboard/api-keys/new?error=… (303).
 *
 * The raw key is rendered into the response body inline — never written to
 * a query parameter, never persisted in the URL, and the page sets
 * Cache-Control: no-store so intermediaries cannot cache it.
 *
 * Implementation note (CI fix): Next.js forbids `react-dom/server` inside
 * Route Handlers ("imports react-dom/server. To fix it, render or return
 * the content directly as a Server Component instead"). The result HTML
 * is therefore built from plain template strings here, with strict
 * HTML-entity escaping for user input. The ApiKeysView module remains
 * the source of truth for the list/form views — only the one-time
 * post-create page lives inline.
 *
 * Spec refs:
 *   §4.1 — API-key auth UI
 *   §5.10 — CSP, no inline scripts, form-action='self'
 *   §2 #20 — no existence leak (we surface only the API's error message)
 *   §2 #22 — keys masked in logs (we never log the raw key here)
 */

import { NextResponse, type NextRequest } from 'next/server';

function apiBaseUrl(): string {
  const explicit = process.env['WILLBUY_API_URL'] ?? process.env['NEXT_PUBLIC_API_URL'];
  if (explicit) return explicit.replace(/\/$/, '');
  return 'http://127.0.0.1:3000';
}

function escapeRedirect(s: string): string {
  // Cap length to avoid header bloat; encodeURIComponent for safety.
  return encodeURIComponent(s.slice(0, 200));
}

// Tight HTML-entity escape — avoids pulling in a dependency. Safe for the
// small set of values we interpolate (label, prefix, raw key).
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Render the one-time "your new key" page as plain HTML. Mirrors
 * NewKeyResultView from ApiKeysView.tsx so the rendered output is
 * indistinguishable to the user — but built without React because Next.js
 * 14 disallows `react-dom/server` in Route Handlers.
 */
function renderResultPage(input: { apiKey: string; label: string; prefix: string }): string {
  const label = esc(input.label);
  const prefix = esc(input.prefix);
  const apiKey = esc(input.apiKey);

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Your new API key — willbuy.dev</title>
    <link rel="stylesheet" href="/_next/static/css/app/layout.css" />
  </head>
  <body class="min-h-screen bg-gray-50">
    <header class="border-b border-gray-200 bg-white">
      <div class="mx-auto flex max-w-5xl items-center justify-between px-6 py-3">
        <a href="/dashboard" class="text-sm font-semibold tracking-tight text-gray-900 hover:text-gray-700">willbuy.dev</a>
        <nav class="flex items-center gap-5 text-sm text-gray-600">
          <a href="/dashboard" class="hover:text-gray-900">Dashboard</a>
          <a href="/dashboard/api-keys" class="hover:text-gray-900">API keys</a>
        </nav>
      </div>
    </header>
    <main>
      <div class="mx-auto max-w-2xl px-6 py-16">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">Your new API key</h1>
        <p class="mt-2 text-sm text-gray-500">
          Label: <span class="font-medium text-gray-700">${label}</span>
          <span class="text-gray-400">(prefix ${prefix}…)</span>
        </p>

        <div role="alert" class="mt-6 rounded-lg border border-yellow-300 bg-yellow-50 px-4 py-3">
          <p class="text-sm font-semibold text-yellow-900">Save this key now — it will not be shown again.</p>
          <p class="mt-1 text-sm text-yellow-800">
            Treat it like a password. Store it in your secrets manager. If you lose it, revoke this key and create a new one.
          </p>
        </div>

        <div class="mt-6">
          <label for="api-key-display" class="block text-xs font-medium uppercase tracking-wide text-gray-500">API key</label>
          <pre id="api-key-display" class="mt-2 overflow-x-auto rounded-md border border-gray-300 bg-gray-50 px-4 py-3 font-mono text-sm text-gray-900">${apiKey}</pre>
        </div>

        <div class="mt-8 flex items-center gap-3">
          <a href="/dashboard/api-keys" class="inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white shadow hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-900 focus:ring-offset-2">
            I have saved this key — done
          </a>
        </div>
      </div>
    </main>
  </body>
</html>`;
}

export async function POST(req: NextRequest): Promise<Response> {
  // Parse form-encoded body. URLSearchParams handles application/x-www-form-urlencoded.
  const form = await req.formData();
  const rawLabel = form.get('label');
  const label = typeof rawLabel === 'string' ? rawLabel.trim() : '';

  if (!label) {
    return NextResponse.redirect(
      new URL('/dashboard/api-keys/new?error=Label+is+required', req.url),
      303,
    );
  }

  const cookieHeader = req.headers.get('cookie') ?? '';
  let res: Response;
  try {
    res = await fetch(`${apiBaseUrl()}/api/api-keys`, {
      method: 'POST',
      headers: {
        cookie: cookieHeader,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ label }),
      cache: 'no-store',
    });
  } catch {
    return NextResponse.redirect(
      new URL(
        `/dashboard/api-keys/new?error=${escapeRedirect('API unreachable, please retry')}`,
        req.url,
      ),
      303,
    );
  }

  if (res.status === 401) {
    return NextResponse.redirect(new URL('/sign-in?redirect=%2Fdashboard%2Fapi-keys%2Fnew', req.url), 303);
  }
  if (!res.ok) {
    let msg = `Could not create key (${res.status})`;
    try {
      const j = (await res.json()) as { error?: string };
      if (j.error) msg = j.error;
    } catch {
      /* ignore parse errors */
    }
    return NextResponse.redirect(
      new URL(`/dashboard/api-keys/new?error=${escapeRedirect(msg)}`, req.url),
      303,
    );
  }

  const body = (await res.json()) as {
    id: number;
    label: string;
    key: string;
    prefix: string;
  };

  const html = renderResultPage({
    apiKey: body.key,
    label: body.label,
    prefix: body.prefix,
  });

  return new NextResponse(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      // Prevent any intermediary or browser back/forward cache from
      // retaining the raw key. Spec §2 #22 — keys are masked everywhere
      // except this one-time response.
      'cache-control': 'no-store, no-cache, must-revalidate, private',
      pragma: 'no-cache',
      // Stop any embed; the key must not appear in iframes.
      'x-frame-options': 'DENY',
    },
  });
}

// GET for this path is not supported — the user lands here only via form POST.
// A bare GET (e.g. via "Back" navigation) sends them to the form.
export async function GET(req: NextRequest): Promise<Response> {
  return NextResponse.redirect(new URL('/dashboard/api-keys/new', req.url), 303);
}
