-- 0015_seed_sqlever_state.sql — HISTORICAL REFERENCE (issue #48, amendment A4 + PR #91).
--
-- This file is HISTORICAL REFERENCE ONLY. See infra/migrations/README.md.
-- The operative source for this migration is
-- `infra/sqlever/deploy/0015_seed_sqlever_state.sql`.
--
-- What this migration actually does (in the operative deploy script):
-- it seeds the legacy `_migrations` shadow row for 0015 so the row count
-- stays consistent with the .sql file count in infra/migrations/ (which
-- the test suite uses as the expected row count).
--
-- It does NOT seed sqlever's own state tables. sqlever manages its own
-- sqitch.* state (sqitch.changes, sqitch.events, sqitch.projects) on its
-- own — this migration does not write to those tables. The bash-to-sqlever
-- transition is handled outside this migration.
--
-- NOTE: This file is intentionally kept in infra/migrations/ so that the
-- legacy _migrations table (and test assertions that count .sql files there)
-- continues to reflect the full migration history. The CI guard
-- (scripts/check-migrations.sh) ensures this file stays in sync with the
-- operative deploy script under infra/sqlever/deploy/.
